"""Trace Behavior Diffing engine."""

import difflib
import json
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

from agent_tracer_plus.core.models import Span, Trace


@dataclass
class SpanDiff:
    """Represents differences between two matched spans or an inserted/deleted span."""
    opcode: str  # "equal", "replace", "insert", "delete"
    base_span: Optional[Span] = None
    compare_span: Optional[Span] = None
    
    # Differences (only populated if opcode is "replace" or "equal")
    status_changed: bool = False
    duration_delta_ms: float = 0.0
    input_changed: bool = False
    input_diff: Any = None
    output_changed: bool = False
    output_diff: Any = None


@dataclass
class TraceDiffReport:
    """Report generated by diffing two traces."""
    base_trace_id: str
    compare_trace_id: str

    duration_delta_ms: float
    cost_delta: float
    token_delta: int

    reasoning_path_changed: bool
    
    # Chronological sequence of span operations
    span_ops: List[SpanDiff]


def _format_for_diff(data: Any) -> str:
    """Format data into a string suitable for unified diffing."""
    if isinstance(data, (dict, list)):
        return json.dumps(data, indent=2, sort_keys=True)
    return str(data) if data is not None else ""


def _text_diff(d1: Any, d2: Any, name: str) -> Optional[str]:
    """Generate a unified diff between two data structures if they differ."""
    s1 = _format_for_diff(d1)
    s2 = _format_for_diff(d2)
    
    if s1 == s2:
        return None
        
    lines1 = s1.splitlines(keepends=True)
    lines2 = s2.splitlines(keepends=True)
    
    diff = list(difflib.unified_diff(
        lines1, lines2, 
        fromfile=f"{name} (base)", 
        tofile=f"{name} (compare)",
        n=3
    ))
    return "".join(diff) if diff else None


def diff_traces(base_trace: Trace, base_spans: List[Span],
                compare_trace: Trace, compare_spans: List[Span]) -> TraceDiffReport:
    """Compare two traces and return a deep diff report using Sequence Alignment."""

    # Sort chronologically to represent the reasoning path sequence
    b_spans = sorted(base_spans, key=lambda s: s.started_at)
    c_spans = sorted(compare_spans, key=lambda s: s.started_at)

    # We align spans based on their name and type
    b_signatures = [f"{s.span_type.value}:{s.name}" for s in b_spans]
    c_signatures = [f"{s.span_type.value}:{s.name}" for s in c_spans]

    matcher = difflib.SequenceMatcher(None, b_signatures, c_signatures)
    
    span_ops = []
    reasoning_path_changed = False

    for opcode, b_start, b_end, c_start, c_end in matcher.get_opcodes():
        if opcode != "equal":
            reasoning_path_changed = True
            
        if opcode == "replace":
            # If lengths match, we can do 1:1 replacement.
            # If they don't, we just pair them up sequentially until one runs out, then treat the rest as insert/delete
            length = min(b_end - b_start, c_end - c_start)
            for i in range(length):
                b_span = b_spans[b_start + i]
                c_span = c_spans[c_start + i]
                span_ops.append(_diff_matched_spans(b_span, c_span, "replace"))
                
            # Remaining are deletions
            for i in range(length, b_end - b_start):
                span_ops.append(SpanDiff(opcode="delete", base_span=b_spans[b_start + i]))
            # Remaining are insertions
            for i in range(length, c_end - c_start):
                span_ops.append(SpanDiff(opcode="insert", compare_span=c_spans[c_start + i]))
                
        elif opcode == "delete":
            for i in range(b_start, b_end):
                span_ops.append(SpanDiff(opcode="delete", base_span=b_spans[i]))
                
        elif opcode == "insert":
            for i in range(c_start, c_end):
                span_ops.append(SpanDiff(opcode="insert", compare_span=c_spans[i]))
                
        elif opcode == "equal":
            for i in range(b_end - b_start):
                b_span = b_spans[b_start + i]
                c_span = c_spans[c_start + i]
                span_ops.append(_diff_matched_spans(b_span, c_span, "equal"))

    return TraceDiffReport(
        base_trace_id=base_trace.trace_id,
        compare_trace_id=compare_trace.trace_id,
        duration_delta_ms=compare_trace.duration_ms - base_trace.duration_ms,
        cost_delta=compare_trace.total_cost - base_trace.total_cost,
        token_delta=compare_trace.total_tokens - base_trace.total_tokens,
        reasoning_path_changed=reasoning_path_changed,
        span_ops=span_ops
    )


def _diff_matched_spans(b_span: Span, c_span: Span, opcode: str) -> SpanDiff:
    in_diff = _text_diff(b_span.input, c_span.input, "input")
    out_diff = _text_diff(b_span.output, c_span.output, "output")

    return SpanDiff(
        opcode=opcode,
        base_span=b_span,
        compare_span=c_span,
        status_changed=(b_span.status != c_span.status),
        duration_delta_ms=c_span.duration_ms - b_span.duration_ms,
        input_changed=in_diff is not None,
        input_diff=in_diff,
        output_changed=out_diff is not None,
        output_diff=out_diff,
    )
